package com.semanticsquare.exceptions;

import java.io.FileNotFoundException;

public class ExceptionsDemo {
	
	public static void main(String[] args) throws FileNotFoundException {	
		System.out.println("\nInside main ...");		
		share();
		try {
			share();
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
		HttpConnect.sendTest(1, "hello", "http://www.goodsnips.com");
		System.out.println("\nEnd of main ...");
	}

	private static void share() throws FileNotFoundException {
		System.out.println("\nInside share ...");
		 HttpConnect.send(1, "hello", "http://www.goodsnips.com");
		 HttpConnect.sendTest(1, "hello", "http://www.goodsnips.com");
//		try {
//			HttpConnect.send(1, "hello", "http://www.goodsnips.com");
//		} catch (FileNotFoundException e) {
//			// TODO Auto-generated catch block
//			 e.printStackTrace();
//		}		
		
		System.out.println("\nEnd of share ...");
	}	
	 
}